#!/bin/sh
set -e
errors=$(/usr/sbin/php5-fpm --fpm-config $1 -t 2>&1 | grep "\[ERROR\]" || true);
if [ -n "$errors" ]; then
    echo "Please fix your configuration file..."
    echo $errors
    exit 1
fi
exit 0
