#!/bin/bash

# Update the site with the latest code push.
GIT_WORK_TREE=/home/warpspeed/sites/{{domain}}/
export GIT_WORK_TREE
git checkout -f

# If a user defined post-receive script exists, run it.
if [ -f "/home/warpspeed/sites/{{domain}}/warpspeed.sh" ]; then
    cd "/home/warpspeed/sites/{{domain}}"
    echo "Running user defined warpspeed.sh file..."
    bash warpspeed.sh
fi
